version: '3.8'

services:

# server
  backend:
    build:
      context: ../../DevOps-with-Docker/1.11-1.14/1.13/example-backend/
    ports:
      - 8080:8080
    environment:
      - REQUEST_ORIGIN=http://localhost:5000
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
    depends_on:
      - redis
      - db

# client
  frontend:
    build:
      context: ../../DevOps-with-Docker/1.11-1.14/1.12/
    ports:
      - 5000:5000
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080    
    depends_on:
      - backend

# Scaling
  redis:
    image: redis

# postgres DB
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./database:/var/lib/postgresql/data