version: '3.8'

services:
  backend:
    build:
      context: ./1.13/example-backend/
    environment:
      - REQUEST_ORIGIN=http://localhost
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
    depends_on:
      - redis
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./1.12/
    environment:
      - REACT_APP_BACKEND_URL=http://localhost/api
    depends_on:
      - backend
    networks:
      - app-network

  redis:
    image: redis
    networks:
      - app-network

  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./database:/var/lib/postgresql/data
    networks:
      - app-network

  proxy:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
